name: 🧊 CI tests

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

jobs:
  test:
    name: 🧊 CI test
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-24.04', 'macos-15', 'windows-2022' ]
        python-version: ['3.10', '3.11.2', '3.12', '3.13']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: test
      env:
        PYTHONWARNINGS: default
        PYTHONUTF8: 1
      run: |
        pytest -s -vv tests example/Shared_Dimensions/shared_dimension_generation/sd_example.py
